require 'arc_weld/resources/asset'
require 'arc_weld/resources/asset_category'
require 'arc_weld/resources/customer'
require 'arc_weld/resources/group'
require 'arc_weld/resources/location'
require 'arc_weld/resources/network'
require 'arc_weld/resources/zone'